version: '3.8'

services:
  web:
    build:
      context: ./NoSiitFastAPI
    restart: on-failure
    env_file:
      - ./NoSiitFastAPI/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`backend.nosiit.live`)"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=letsencrypt"
  traefik:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./services/traefik/traefik.prod.toml:/etc/traefik/traefik.toml"    
      - "./services/traefik/acme.json:/acme.json"
